### ISSUE TITLE
Virus detection

### ISSUE THREAD

**Issue by dedmen** [gyf304/partylan#5]
I tried to download the latest Release, and even my browser refused the download.

VirusTotal answers why: 
https://www.virustotal.com/gui/file/c40389ebe232674195ba0d61fcf0018e511d3ca63e5dbdca89cbfc2aaf4491e1
https://www.virustotal.com/gui/file/6ef9367ef41da14edd1be89f216e643300057c9bea69755c73dab71754ab9f3e (lpvpn.exe)

![firefox_2024-05-23_14-12-02](https://github.com/gyf304/partylan/assets/3768165/9117a9d2-5cc1-462a-9da8-648daf18e121)

What is up with this?

**Comment by gyf304** [comment]
To be completely honest - I don't know. The program requires administrator access and configures network interfaces, maybe that's considered high-risk for some anti-virus solutions.
The entire project is open-source including the build pipeline, so people can check that there's nothing nefarious going on here.
